# Generated by Django 3.1.7 on 2021-03-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='update',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
