# Generated by Django 3.1.7 on 2021-03-05 17:45

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('Blog_apps', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='taggs',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
