# Generated by Django 3.1.7 on 2021-03-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_apps', '0004_post_taggs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='taggs',
            new_name='tags',
        ),
    ]
